serviceMaps:
  serviceName: product
  mappings:
  - version: 1.0
    description: Persists Product
    fromTopic: oy-save-product-topic
    isTransaction: true
    isAuditEnabled: true
    module: PRODUCT
    objecIdJsonPath: $.id
    tenantIdJsonPath: $.tenantId
    transactionCodeJsonPath: $.id
    userUuidJsonPath: $.[0].auditDetails.createdBy
    auditAttributeBasePath: $.*
    queryMaps:
    - query: INSERT INTO oy.product(id, tenantId, type, name, manufacturer, additionalDetails,
        createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion, isDeleted)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.*
      jsonMaps:
      - jsonPath: $.*.id
      - jsonPath: $.*.tenantId
      - jsonPath: $.*.type
      - jsonPath: $.*.name
      - jsonPath: $.*.manufacturer
      - jsonPath: $.*.additionalFields
        type: JSON
        dbType: JSONB
      - jsonPath: $.*.auditDetails.createdBy
      - jsonPath: $.*.auditDetails.lastModifiedBy
      - jsonPath: $.*.auditDetails.createdTime
      - jsonPath: $.*.auditDetails.lastModifiedTime
      - jsonPath: $.*.rowVersion
      - jsonPath: $.*.isDeleted
  - version: 1.0
    description: Updates Product
    fromTopic: oy-update-product-topic
    isTransaction: true
    isAuditEnabled: true
    module: PRODUCT-UPDATE
    objecIdJsonPath: $.id
    tenantIdJsonPath: $.tenantId
    transactionCodeJsonPath: $.id
    userUuidJsonPath: $.[0].auditDetails.lastModifiedBy
    auditAttributeBasePath: $.*
    queryMaps:
    - query: UPDATE oy.product SET tenantId = ?, type = ?, name = ?, manufacturer
        = ?, additionalDetails = ?, lastModifiedBy = ?, lastModifiedTime = ?, rowVersion
        = ?, isDeleted = ? WHERE id = ?
      basePath: $.*
      jsonMaps:
      - jsonPath: $.*.tenantId
      - jsonPath: $.*.type
      - jsonPath: $.*.name
      - jsonPath: $.*.manufacturer
      - jsonPath: $.*.additionalFields
        type: JSON
        dbType: JSONB
      - jsonPath: $.*.auditDetails.lastModifiedBy
      - jsonPath: $.*.auditDetails.lastModifiedTime
      - jsonPath: $.*.rowVersion
      - jsonPath: $.*.isDeleted
      - jsonPath: $.*.id
  - version: 1.0
    description: Saves a product variant
    fromTopic: oy-save-product-variant-topic
    isTransaction: true
    isAuditEnabled: true
    module: PRODUCT-VARIANT
    objecIdJsonPath: $.id
    tenantIdJsonPath: $.tenantId
    transactionCodeJsonPath: $.id
    userUuidJsonPath: $.[0].auditDetails.createdBy
    auditAttributeBasePath: $.*
    queryMaps:
    - query: INSERT INTO oy.product_variant(id, tenantId, productId, sku, variation,
        additionalDetails, createdBy, lastModifiedBy, createdTime, lastModifiedTime,
        rowVersion, isDeleted) VALUES (?,?,?,?,?,?,?,?,?,?,?,?);
      basePath: $.*
      jsonMaps:
      - jsonPath: $.*.id
      - jsonPath: $.*.tenantId
      - jsonPath: $.*.productId
      - jsonPath: $.*.sku
      - jsonPath: $.*.variation
      - jsonPath: $.*.additionalFields
        type: JSON
        dbType: JSONB
      - jsonPath: $.*.auditDetails.createdBy
      - jsonPath: $.*.auditDetails.lastModifiedBy
      - jsonPath: $.*.auditDetails.createdTime
      - jsonPath: $.*.auditDetails.lastModifiedTime
      - jsonPath: $.*.rowVersion
      - jsonPath: $.*.isDeleted
  - version: 1.0
    description: Updates a product variant
    fromTopic: oy-update-product-variant-topic
    isTransaction: true
    isAuditEnabled: true
    module: PRODUCT-UPDATE
    objecIdJsonPath: $.id
    tenantIdJsonPath: $.tenantId
    transactionCodeJsonPath: $.id
    userUuidJsonPath: $.[0].auditDetails.lastModifiedBy
    auditAttributeBasePath: $.*
    queryMaps:
    - query: UPDATE oy.product_variant SET tenantId = ?, productId = ?, sku = ?, variation
        = ?, additionalDetails = ?, lastModifiedBy = ?, lastModifiedTime = ?, rowVersion
        = ?, isDeleted = ? WHERE id = ?;
      basePath: $.*
      jsonMaps:
      - jsonPath: $.*.tenantId
      - jsonPath: $.*.productId
      - jsonPath: $.*.sku
      - jsonPath: $.*.variation
      - jsonPath: $.*.additionalFields
        type: JSON
        dbType: JSONB
      - jsonPath: $.*.auditDetails.lastModifiedBy
      - jsonPath: $.*.auditDetails.lastModifiedTime
      - jsonPath: $.*.rowVersion
      - jsonPath: $.*.isDeleted
      - jsonPath: $.*.id
