ServiceMaps:
  serviceName: product
  version: 1.0.0
  mappings:
  - topic: ba-save-product-variant-topic
    configKey: INDEX
    indexes:
    - name: ba-product-variant-index-v1
      type: product-variant
      id: $.id
      isBulk: true
      jsonPath: $.*
      timeStampField: $.auditDetails.createdTime
  - topic: ba-save-product-topic
    configKey: INDEX
    indexes:
    - name: ba-product-index-v1
      type: product
      id: $.id
      isBulk: true
      jsonPath: $.*
      timeStampField: $.auditDetails.createdTime
  - topic: ba-update-product-topic
    configKey: INDEX
    indexes:
    - name: ba-product-index-v1
      type: product
      id: $.id
      isBulk: true
      jsonPath: $.*
      timeStampField: $.auditDetails.createdTime
  - topic: ba-update-product-variant-topic
    configKey: INDEX
    indexes:
    - name: ba-product-variant-index-v1
      type: product-variant-update
      id: $.id
      isBulk: true
      jsonPath: $.*
      timeStampField: $.auditDetails.createdTime
